### ISSUE TITLE
Throw warning instead of error if package does not exist in repo

### ISSUE THREAD

**Issue by sigveo** [vexx32/choco-ansible#178]
### Checklist

- [x] I have verified this is the correct repository for opening this issue.
- [x] I have verified no other issues exist related to my request.

### Is Your Feature Request Related To A Problem? Please describe.

If you have an existing environment with a lot of installed programs already, using `choco sync` is very convenient to make Chocolatey "take over" these packages. However, choco sync takes over all installed programs on the machine, even if you don't have a chocolatey package for it in your internal repo. 

If you then run a task to upgrade all installed packages, the task upgrades the packages that you have in your internal repo, but the task fails if you have some programs installed that you do not have a chocolatey package for in your internal repo.

```
- name: Upgrade installed packages
  win_chocolatey:
    name: all
    state: latest
```

### Describe The Solution. Why is it needed?

I think that the module should warn you if no package was found in internal repo instead of failing the task, to better reflect that som packages was upgraded, but some packages was not found.

**Comment by Windos** [comment]
Hi @sigveo, I'm trying to repro this locally and I thought doing so on my local machine would be fine... but I have so many packages installed that it's taking a while!

What I will say though is that this is already possible via a Chocolatey CLI flag (`--ignore-unfound`) to ignore packages not found in your sources which you can call via the Ansible module like so:

```yaml
- name: Upgrade installed packages
  win_chocolatey:
    name: all
    state: latest
    choco_args:
    - --ignore-unfound
```

It's also possible to change this globally via a feature which you can enable via Ansible like this:

```yaml
- name: Enable ignoring unfound packages
  win_chocolatey_feature:
    name: ignoreUnfoundPackagesOnUpgradeOutdated 
    state: enable
```

I will close out this issue as I don't think there's any changes to make of the back of this, but please do pop a comment here if you disagree with that.
